spring.application.name=baitap06
# Server
server.port=8080
spring.thymeleaf.cache=false

# K?t n?i SQL Server (s?a user/pass theo máy b?n)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DBUser;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
  # b?ng ?ã t?n t?i trong DBUser -> không t? ??i schema
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

